include makefiles/options.mk

include makefiles/instrument.mk

include makefiles/files.mk
include makefiles/aliases.mk
include makefiles/commands.mk
include makefiles/compile.mk
include makefiles/archive.mk
